const {
    defineConfig,
} = require("eslint/config");

const globals = require("globals");

module.exports = defineConfig([{
    plugins: {},

    languageOptions: {
        globals: {
            ...globals.browser,
            ...globals.node,
            ...globals.commonjs,
            ...globals["shared-node-browser"],
            ...globals.worker,
            ...globals.amd,
            ...globals.mocha,
            ...globals.jasmine,
            ...globals.jest,
            ...globals.phantomjs,
            ...globals.protractor,
            ...globals.qunit,
            ...globals.jquery,
            ...globals.prototypejs,
            ...globals.shelljs,
            ...globals.meteor,
            ...globals.mongo,
            ...globals.applescript,
            ...globals.nashorn,
            ...globals.serviceworker,
            ...globals.atomtest,
            ...globals.embertest,
            ...globals.webextensions,
            ...globals.greasemonkey,
        },
    },

    rules: {
        "react/react-in-jsx-scope": "off",
        "no-cond-assign": "error",
        "no-console": "error",
        "no-constant-condition": "error",
        "no-control-regex": "error",
        "no-debugger": "error",
        "no-dupe-args": "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-empty": "error",
        "no-empty-character-class": "error",
        "no-ex-assign": "error",
        "no-extra-boolean-cast": "error",
        "no-extra-parens": "off",
        "no-extra-semi": "error",
        "no-func-assign": "error",
        "no-inner-declarations": "error",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "error",
        "no-negated-in-lhs": "off",
        "no-obj-calls": "error",
        "no-prototype-builtins": "off",
        "no-regex-spaces": "error",
        "no-sparse-arrays": "error",
        "no-unexpected-multiline": "error",
        "no-unreachable": "error",
        "no-unsafe-finally": "error",
        "use-isnan": "error",
        "valid-jsdoc": "off",
        "valid-typeof": "error",
        "accessor-pairs": "off",
        "array-callback-return": "off",
        "block-scoped-var": "off",
        complexity: "off",
        "consistent-return": "off",
        curly: "off",
        "default-case": "off",
        "dot-location": "off",
        "dot-notation": "off",
        eqeqeq: "off",
        "guard-for-in": "off",
        "no-alert": "off",
        "no-caller": "off",
        "no-case-declarations": "error",
        "no-div-regex": "off",
        "no-else-return": "off",
        "no-empty-function": "off",
        "no-empty-pattern": "error",
        "no-eq-null": "off",
        "no-eval": "off",
        "no-extend-native": "off",
        "no-extra-bind": "off",
        "no-extra-label": "off",
        "no-fallthrough": "error",
        "no-floating-decimal": "off",
        "no-implicit-coercion": "off",
        "no-implicit-globals": "off",
        "no-implied-eval": "off",
        "no-invalid-this": "off",
        "no-iterator": "off",
        "no-labels": "off",
        "no-lone-blocks": "off",
        "no-loop-func": "off",
        "no-magic-numbers": "off",
        "no-multi-spaces": "off",
        "no-multi-str": "off",
        "no-native-reassign": "off",
        "no-new": "off",
        "no-new-func": "off",
        "no-new-wrappers": "off",
        "no-octal": "error",
        "no-octal-escape": "off",
        "no-param-reassign": "off",
        "no-proto": "off",
        "no-redeclare": "error",
        "no-return-assign": "off",
        "no-script-url": "off",
        "no-self-assign": "error",
        "no-self-compare": "off",
        "no-sequences": "off",
        "no-throw-literal": "off",
        "no-unmodified-loop-condition": "off",
        "no-unused-expressions": "off",
        "no-unused-labels": "error",
        "no-useless-call": "off",
        "no-useless-concat": "off",
        "no-useless-escape": "error",
        "no-void": "off",
        "no-warning-comments": "off",
        "no-with": "off",
        radix: "off",
        "vars-on-top": "off",
        "wrap-iife": "off",
        yoda: "off",
        strict: "off",
        "init-declarations": "off",
        "no-catch-shadow": "off",
        "no-delete-var": "error",
        "no-label-var": "off",
        "no-restricted-globals": "off",
        "no-shadow": "off",
        "no-shadow-restricted-names": "off",
        "no-undef": "error",
        "no-undef-init": "off",
        "no-undefined": "off",
        "no-unused-vars": "error",
        "no-use-before-define": "off",
        "callback-return": "off",
        "global-require": "off",
        "handle-callback-err": "off",
        "no-mixed-requires": "off",
        "no-new-require": "off",
        "no-path-concat": "off",
        "no-process-env": "off",
        "no-process-exit": "off",
        "no-restricted-modules": "off",
        "no-sync": "off",
        "array-bracket-spacing": "off",
        "block-spacing": "off",
        "brace-style": "off",
        camelcase: "off",
        "comma-dangle": "off",
        "comma-spacing": "off",
        "comma-style": "off",
        "computed-property-spacing": "off",
        "consistent-this": "off",
        "eol-last": "off",
        "func-names": "off",
        "func-style": "off",
        "id-blacklist": "off",
        "id-length": "off",
        "id-match": "off",
        indent: "off",
        "jsx-quotes": "off",
        "key-spacing": "off",
        "keyword-spacing": "off",
        "linebreak-style": "off",
        "lines-around-comment": "off",
        "max-depth": "off",
        "max-len": "off",
        "max-lines": "off",
        "max-nested-callbacks": "off",
        "max-params": "off",
        "max-statements": "off",
        "max-statements-per-line": "off",
        "multiline-ternary": "off",
        "new-cap": "off",
        "new-parens": "off",
        "newline-after-var": "off",
        "newline-before-return": "off",
        "newline-per-chained-call": "off",
        "no-array-constructor": "off",
        "no-bitwise": "off",
        "no-continue": "off",
        "no-inline-comments": "off",
        "no-lonely-if": "off",
        "no-mixed-operators": "off",
        "no-mixed-spaces-and-tabs": "error",
        "no-multiple-empty-lines": "off",
        "no-negated-condition": "off",
        "no-nested-ternary": "off",
        "no-new-object": "off",
        "no-plusplus": "off",
        "no-restricted-syntax": "off",
        "no-spaced-func": "off",
        "no-ternary": "off",
        "no-trailing-spaces": "off",
        "no-underscore-dangle": "off",
        "no-unneeded-ternary": "off",
        "no-whitespace-before-property": "off",
        "object-curly-newline": "off",
        "object-curly-spacing": "off",
        "object-property-newline": "off",
        "one-var": "off",
        "one-var-declaration-per-line": "off",
        "operator-assignment": "off",
        "operator-linebreak": "off",
        "padded-blocks": "off",
        "quote-props": "off",
        quotes: "off",
        "require-jsdoc": "off",
        semi: "off",
        "semi-spacing": "off",
        "sort-vars": "off",
        "space-before-blocks": "off",
        "space-before-function-paren": "off",
        "space-in-parens": "off",
        "space-infix-ops": "off",
        "space-unary-ops": "off",
        "spaced-comment": "off",
        "unicode-bom": "off",
        "wrap-regex": "off",
        "arrow-body-style": "off",
        "arrow-parens": "off",
        "arrow-spacing": "off",
        "constructor-super": "error",
        "generator-star-spacing": "off",
        "no-class-assign": "error",
        "no-confusing-arrow": "off",
        "no-const-assign": "error",
        "no-dupe-class-members": "error",
        "no-duplicate-imports": "off",
        "no-new-symbol": "error",
        "no-restricted-imports": "off",
        "no-this-before-super": "error",
        "no-useless-computed-key": "off",
        "no-useless-constructor": "off",
        "no-useless-rename": "off",
        "no-var": "off",
        "object-shorthand": "off",
        "prefer-arrow-callback": "off",
        "prefer-const": "off",
        "prefer-reflect": "off",
        "prefer-rest-params": "off",
        "prefer-spread": "off",
        "prefer-template": "off",
        "require-yield": "error",
        "rest-spread-spacing": "off",
        "sort-imports": "off",
        "template-curly-spacing": "off",
        "yield-star-spacing": "off",
    },

    parserOpts: {},
}]);
