export const QUERY_KEYS = {
  profile: 'profile',
  projects: 'projects',
  deviceTemplates: 'deviceTemplates',
  physicalDevices: 'physicalDevices',
  ports: 'ports',
  task: 'task',
  buildings: 'buildings',
  floors: 'floors',
  users: 'users',
  rooms: 'rooms',
  topology: 'topology',
  logicalDevices: 'logicalDevices',
  racks: 'racks',
};
