name: CE-cloud prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ce-cloud
    environment: ce-cloud
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create .env file
        run: |
          echo "NODE_ENV=${{ vars.NODE_ENV }}" >> .env
          echo "NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}" >> .env
          echo "NEXT_PUBLIC_APP_URL=${{ vars.NEXT_PUBLIC_APP_URL }}" >> .env

      - name: Deploy docker-compose stack
        run: docker compose -f docker-compose.prod.yaml up -d --build --force-recreate

      - name: Prune Docker System
        run: docker system prune -af
