name: CICD Staging

on:
  push:
    branches:
      - develop

env:
  NODE_ENV: ${{ secrets.NODE_ENV }}
  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "NODE_ENV=${NODE_ENV}" >> .env
          echo "NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}" >> .env

      - name: Deploy docker-compose stack
        run: docker compose up -d --build --force-recreate

      - name: Prune Docker System
        run: docker system prune -af
